openapi: "3.0.0"
servers:
  - url: "https://ejp-rd/catalogueDirectory/" # to be added
info:
  version: "0.1"
  title: "EJP-RD Central Catalogue Directory API"
  description: >-
    "The EJP-RD Central Catalogue Directory API is a web service providing a
     REST API to fetch, add and remove catalogue addresses to or from the
     central catalogue directory."
  contact:
    name: "Magic Mike" # to be added
    email: "someone@ejp.com" # to be added
  #license: # to be determined
  #name: "Apache 2.0"
  #url: "http://www.apache.org/licenses/LICENSE-2.0.html"
externalDocs:
  
  description: "EJP-RD Website"
  url: https://www.ejprarediseases.org/"
paths:
  /:
    get:
      description: "Get information about the EJP-RD Central Catalogue Directory API."
      operationId: "getInformation"
      responses:
        "200":
          description: "successful operation"
          headers:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InfoResponse"
        "404":
          description: "not found"
          headers:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        default:
          description": "unexpected error"
          headers:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /catalogues:
    get:
      description: "Get all stored catalogues."
      operationId: "getCatalogues"
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/DataResponse"
        "400":
          description: Bad request (e.g. missing mandatory parameter)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: >-
            Unauthorised (e.g. when an unauthenticated user tries to access a
            protected catalogue.)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: >-
            Forbidden (e.g. the catalogue is protected for all users or the user
            is authenticated but s/he is not granted for this catalogue)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: "not found"
          headers:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        default:
          description": "unexpected error"
          headers:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /catalogues/biobanks:
    get:
      description: "Get all stored biobank catalogues."
      operationId: "getBiobanks"
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/DataResponse"
        "400":
          description: Bad request (e.g. missing mandatory parameter)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: >-
            Unauthorised (e.g. when an unauthenticated user tries to access a
            protected catalogue.)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: >-
            Forbidden (e.g. the catalogue is protected for all users or the user
            is authenticated but s/he is not granted for this catalogue)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: "not found"
          headers:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        default:
          description": "unexpected error"
          headers:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /catalogues/registries:
    get:
      description: "Get all stored registry catalogues."
      operationId: "getRegistries"
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/DataResponse"
        "400":
          description: Bad request (e.g. missing mandatory parameter)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: >-
            Unauthorised (e.g. when an unauthenticated user tries to access a
            protected catalogue.)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: >-
            Forbidden (e.g. the catalogue is protected for all users or the user
            is authenticated but s/he is not granted for this catalogue)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: "not found"
          headers:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        default:
          description": "unexpected error"
          headers:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /catalogues/$ID:
    get:
      description: "Get catalogue with $ID."
      operationId: "getCatalogueByID"
      parameters:
        - name: id
          description: "The unique identifier of the catalogue."
          in: path
          required: true
          schema:
            type:
              type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/DataResponse"
        "400":
          description: Bad request (e.g. missing mandatory parameter)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: >-
            Unauthorised (e.g. when an unauthenticated user tries to access a
            protected catalogue.)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: >-
            Forbidden (e.g. the catalogue is protected for all users or the user
            is authenticated but s/he is not granted for this catalogue)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: "not found"
          headers:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        default:
          description": "unexpected error"
          headers:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /addCatalogue:
    post:
      description: "Add a new catalogue to the central catalogue directory."
      operationId: "addCatalogue"
      parameters:
        - name: catalogueType
          description: "The type of the catalogue e.g. biobank."
          in: query
          required: true
          schema:
            type:
              type: string
        - name: catalogueName
          description: "The name of the catalogue."
          in: query
          required: true
          schema:
            name:
              type: string
        - name: catalogueAddress
          description: "The address of the catalogue."
          in: query
          required: true
          schema:
            address:
              type: url
        - name: catalogueDescription
          description: "The short description of the catalogue."
          in: query
          required: true
          schema:
            address:
              type: url
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/SuccessResponse"
        "400":
          description: Bad request (e.g. missing mandatory parameter)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: >-
            Unauthorised (e.g. when an unauthenticated user tries to access a
            protected catalogue.)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: >-
            Forbidden (e.g. the catalogue is protected for all users or the user
            is authenticated but s/he is not granted for this catalogue)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        default:
          description": "unexpected error"
          headers:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /removeCatalogue:
    post:
      description: "Remove an existing catalogue from the central catalogue directory."
      operationId: "removeCatalogue"
      parameters:
        - name: id
          description: "The unique identifier of the recource."
          in: query
          required: true
          schema:
            type:
              type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/SuccessResponse"
        "400":
          description: Bad request (e.g. missing mandatory parameter)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: >-
            Unauthorised (e.g. when an unauthenticated user tries to access a
            protected catalogue.)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: >-
            Forbidden (e.g. the catalogue is protected for all users or the user
            is authenticated but s/he is not granted for this catalogue)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: "Not found (e.g. the catalogue to be removed is not in the directory)"
          headers:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        default:
          description": "unexpected error"
          headers:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
components:
  schemas:
    InfoResponse:
      type: object
      required:
        - name
        - description
        - usage
        - apiVersion
      properties:
        name:
          type: string
          description: Name of the API.
        description:
          type: string
          description: Description of the API.
        usage:
          type: string
          description: Description on how to use the API.
        apiVersion:
          type: string
          description: Version of the API.
          example: v0.3
    SuccessResponse:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
          example: The http status text.
        data:
          type: string
          example: The id of a catalogue after it has been added.
    ErrorResponse:
      type: "object"
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
          example: The http status text.
    DataResponse:
      type: object
      required:
        - resources
      properties:
        resources:
          type: array
          $ref: "#/components/schemas/Resource"
    Resource:
      type: object
      required:
        - id
        - name
        - description
        - url
        - createDateTime
      properties:
        id:
          type: string
          description: Unique identifier of the ressource.
        name:
          type: string
          description: Name of the ressource.
        description:
          type: string
          description: Description of the resource.
        url:
          type: string
          description: >-
            URL to the ressource.
        createDateTime:
          type: string
          description: The time the resource was created (ISO 8601 format).
          example: "2012-07-29 or 2017-01-17T20:33:40Z"
        updateDateTime:
          type: string
          description: The time the resource was last updated (ISO 8601 format).
          example: "2012-07-19 or 2017-01-17T20:33:40Z"
        version:
          type: string
          description: Version of the ressource.
